server:
  port: 8083
  error:
    include-message: always
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/kanban_service?createDatabaseIfNotExist=true
  application:
    name: kanban-board-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost