
server:
  port: 8090
  error:
    include-message: always
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/kanban_service?createDatabaseIfNotExist=true
  application:
    name: eurekaKanbanService
  mail:
    host: smtp.gmail.com
    port: 587
    username: kanban.board.546@gmail.com
    password: pfilouoeiwygtccx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#            required: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
